In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('ground_truth.csv')
df.head(5)

,Skills,Job Industry,Course Title,Course Description,Course Category,Course Subcategory,Skills Achieved,Course Modules,Similarity Score,Ground Truth
0,"UI/UX, User Research, Figma, Adobe XD, Color T...",Design & Creative,UX: Visual Design Process,No Description,Computer Science,Design and Product,"Prototyping, Design Elements And Principles, U...","Visual Design Foundations: In this module, we ...",0.645067,1
1,"UI/UX, User Research, Figma, Adobe XD, Color T...",Design & Creative,UX Web Design: Build User-Centric Websites,No Description,Computer Science,Design and Product,"User Research, Graphic and Visual Design, User...",Introduction to User Experience (UX): In this ...,0.623015,1
2,"UI/UX, User Research, Figma, Adobe XD, Color T...",Design & Creative,User Research and Design,This course is part of User Interface Design S...,Computer Science,Design and Product,"People Analytics, Data Collection, Statistical...",Preface: Note that weeks 1 and 2 form a cohesi...,0.615718,1
3,"UI/UX, User Research, Figma, Adobe XD, Color T...",Design & Creative,"Designing, Running, and Analyzing Experiments",This course is part of Interaction Design Spec...,Computer Science,Design and Product,"Usability Testing, Statistical Analysis, Stati...",Basic Experiment Design Concepts: In this modu...,0.615713,1
4,"UI/UX, User Research, Figma, Adobe XD, Color T...",Design & Creative,Advanced UX Strategies for Product Managers,No Description,Computer Science,Design and Product,"Storytelling, Usability Testing, User Centered...",Advanced UX Strategies for Product Managers: I...,0.602523,1

In [3]:
grouped = df.groupby(['Skills', 'Job Industry'])

records = []

for (skills, industry), group in grouped:
    top_10 = group.sort_values(by='Similarity Score', ascending=False).head(10)
    relevant = top_10['Ground Truth'].sum()
    precision = relevant / 10

    records.append({
        'Skills': skills,
        'Job Industry': industry,
        'Precision@10': precision
    })

result_df = pd.DataFrame(records)

test_case_fields = [
    "Project Management",
    "Front-end Development",
    "Cybersecurity",
    "Digital Marketing",
    "Data Science",
    "UI/UX Design",
    "Game Development"
]

result_df['Test Case Field'] = test_case_fields
result_df = result_df[['Test Case Field', 'Precision@10']]
result_df

         Test Case Field  Precision@10
0     Project Management           0.4
1  Front-end Development           0.7
2          Cybersecurity           0.8
3      Digital Marketing           0.9
4           Data Science           0.7
5           UI/UX Design           0.8
6       Game Development           0.7

In [4]:
average_precision = result_df['Precision@10'].mean()
print(f"\nAverage Precision@10: {average_precision:.4f}")

Average Precision@10: 0.7143